---
version: "3.2"
services:
  portal:
    build:
      context: .
      dockerfile: .pipeline/local.Dockerfile
    image: "wmdevportal:local"
    user: somebody
    working_dir: /srv/app
    command:
      - bash
      - -c
      - >-
        poetry run mkdocs --verbose build &&
        exec nginx -c /srv/app/contrib/nginx/nginx.conf
    volumes:
      - type: bind
        source: .
        target: /srv/app
        consistency: cached
    ports:
      - "${PORTAL_HTTP_PORT:-9000}:9000"
    restart: always
